--------------------------------------------------------
--  File created - niedziela-paüdziernika-18-2020   
--------------------------------------------------------
DROP TABLE "C##TKUCZAK"."LOAD_STATUS";
--------------------------------------------------------
--  DDL for Table LOAD_STATUS
--------------------------------------------------------

  CREATE TABLE "C##TKUCZAK"."LOAD_STATUS" 
   (	"RUN_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OPEN_DTTM" TIMESTAMP (6) DEFAULT current_timestamp, 
	"CLOSE_DTTM" TIMESTAMP (6), 
	"COMMENTS" VARCHAR2(1024 BYTE), 
	"ETL_CODE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RUN_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TKUCZAK"."RUN_ID_PK" ON "C##TKUCZAK"."LOAD_STATUS" ("RUN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOAD_STATUS
--------------------------------------------------------

  ALTER TABLE "C##TKUCZAK"."LOAD_STATUS" MODIFY ("RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TKUCZAK"."LOAD_STATUS" MODIFY ("OPEN_DTTM" NOT NULL ENABLE);
  ALTER TABLE "C##TKUCZAK"."LOAD_STATUS" ADD CONSTRAINT "RUN_ID_PK" PRIMARY KEY ("RUN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##TKUCZAK"."LOAD_STATUS" MODIFY ("ETL_CODE" NOT NULL ENABLE);
